### ISSUE TITLE
secret management externalisieren

### ISSUE THREAD

**Issue by dOn-MoP** [Stachelritter/CheckMK-PowerShell#2]
Hallo,

aktuell wird das secret/passwort innerhalb des Moduls in der Funktion "Get-CMKHeader" verwaltet.
Es wird hier eine Passwortdatei im Benutzerprofil angelegt - Das Passwort muss dabei regelmäßig (hard coded alle 185 Tage) erneuert werden.
Ausnahmen für bestimmte Benutzernamen sind auch wiederum im code hinterlegt:
Zeile 98: `(($env:username -like '*$') -or ($Username -eq 'automation'))`

Das erschwert Automatisierungen und Nutzung verschiedener automations-user, die andere usernames haben.

Das secret management sollte grundsätzlich außerhalb dieses Moduls stattfinden, dann wäre die Nutzung von z.B. KeePass-APIs, powershell secretstore oder anderen Passwort-Managern, einschließlich des hier abgebildeten Konstrukts möglich.

Als Vorschlag würde ich in der Funktion `Get-CMKConnection` neben dem Parameter `$Username` zusätzlich einen Parameter `[SecureString]$Secret` einführen, an welchen das Passwort übergeben wird.

Was sagst du dazu?
Ich kann gern einen Pull request dazu einstellen.

**Comment by Stachelritter** [comment]
Der Vorschlag klingt gut, an `Get-CMKConnection` kann auch ein PSCredential-Objekt oder der von dir vorgeschlagene SecureString übergeben werden. 
Mein Gedanke an der bisher vorhandenen Methode ist der, dass man als interaktiver Nutzer sein Kennwort fast nie eingeben braucht, wenn die Passwortdatei vorhanden ist (billiges SSO).
Du darfst gerne einen Vorschlag einreichen, andernfalls (wird aber etwas dauern) schaue ich mir das auch gerne an.

**Comment by dOn-MoP** [comment]
Hallo. Das mit dem Secret ist umgesetzt. 

Hinweis: Mein letzter commit (service state Filter für Get-CMKService) ist automatisch im aktuellen pull request gelandet. Sorry für die mögliche Verwirrung..
